# Generated by Django 4.0.6 on 2022-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_remove_slot_court_slot_court_remove_slot_sport_and_more'),
        ('users', '0002_staff_member_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slots',
            field=models.ManyToManyField(blank=True, to='sports.slot'),
        ),
    ]
