# Generated by Django 4.1 on 2022-08-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_remove_slot_court_remove_slot_sport_slot_court_and_more'),
        ('users', '0003_member_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='slots',
            field=models.ManyToManyField(blank=True, to='sports.slot'),
        ),
        migrations.AddField(
            model_name='staff',
            name='slots',
            field=models.ManyToManyField(blank=True, to='sports.slot'),
        ),
    ]
