# Generated by Django 4.0.6 on 2022-08-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courts.court')),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
    ]
