# Generated by Django 4.0.6 on 2022-08-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('sports', '0002_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='court',
        ),
        migrations.AddField(
            model_name='slot',
            name='court',
            field=models.ManyToManyField(blank=True, to='courts.court'),
        ),
        migrations.RemoveField(
            model_name='slot',
            name='sport',
        ),
        migrations.AddField(
            model_name='slot',
            name='sport',
            field=models.ManyToManyField(blank=True, to='sports.sport'),
        ),
    ]
