# Generated by Django 4.1 on 2022-08-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_remove_slot_court_slot_court_remove_slot_sport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.slot')),
            ],
        ),
    ]
