# Generated by Django 4.0.6 on 2022-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_remove_slot_court_remove_slot_sport_slot_court_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
