# Generated by Django 4.0.6 on 2022-08-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_featuredmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_slot',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='booked_slot',
            name='slot',
        ),
        migrations.AddField(
            model_name='booked_slot',
            name='slots',
            field=models.ManyToManyField(blank=True, to='sports.slot'),
        ),
    ]
